### ISSUE TITLE
Help wanted getting error

### ISSUE THREAD

**Issue by Saikatsaha1996** [firoorg/sgminer#11]
![Screenshot_2021-07-08-01-52-41-739_com termux](https://user-images.githubusercontent.com/72664192/124824114-92bb5500-df8f-11eb-9512-9b373dcff469.jpg)

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-07-08-01-29-04-747_com termux](https://user-images.githubusercontent.com/72664192/124821091-e88dfe00-df8b-11eb-982d-354a60adf082.jpg)

**Comment by djm34** [comment]
try removing the #include "immintrin.h", this is for AVX/SSE instructions, not sure you can use it or if it exists for android

**Comment by djm34** [comment]
please don't open a issue for every single problem you get... keep everything in only one

**Comment by Saikatsaha1996** [comment]
Ok sorry for this

**Comment by Saikatsaha1996** [comment]
error: expected ',' or ';' before '__asm__'
   60 | int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);

Can you tell me what is this error?

**Comment by Saikatsaha1996** [comment]
This one
![124824114-92bb5500-df8f-11eb-9512-9b373dcff469](https://user-images.githubusercontent.com/72664192/125175803-2d17d480-e1ec-11eb-8806-1ad5370f551d.jpg)

**Comment by Saikatsaha1996** [comment]
Actually android does not support pthread cancel
Without pthread cancel any solution available?

**Comment by djm34** [comment]
what does pthread cancel ?

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-07-12-15-45-11-406_com miui gallery](https://user-images.githubusercontent.com/72664192/125271341-432aaf80-e328-11eb-9a1d-177a69d263f8.jpg)

**Comment by djm34** [comment]
you just need to go through pthread android version and see how is called "PTHREAD_CANCEL_ASYNCHRONOUS". in principle it is just a number passed as parameter...

**Comment by Saikatsaha1996** [comment]
> you just need to go through pthread android version and see how is called "PTHREAD_CANCEL_ASYNCHRONOUS". in principle it is just a number passed as parameter...

Can you share any link about it?..

**Comment by Saikatsaha1996** [comment]
> you just need to go through pthread android version and see how is called "PTHREAD_CANCEL_ASYNCHRONOUS". in principle it is just a number passed as parameter...

https://github.com/tux-mind/libbthread

Please can you edit code with this.. ?
