### ISSUE TITLE
Please add support m7m

### ISSUE THREAD

**Issue by Saikatsaha1996** [firoorg/sgminer#13]
@djm34 Can you add support for m7m algo ?

**Comment by djm34** [comment]
for what coin ? 
also as far as I know m7m is cpu only

**Comment by Saikatsaha1996** [comment]
m7m --- XMG coin
verushash --- VRSC coin

@djm34  i hope you can add..

Can you add ?

**Comment by djm34** [comment]
anything else  ? :D 
xmg profitability is pretty much 0 and vrsc is not m7m

**Comment by Saikatsaha1996** [comment]
> anything else ? :D xmg profitability is pretty much 0 and vrsc is not m7m

Yes but Verushash algo for VRSC coin profitable.. can you add ?

**Comment by djm34** [comment]
you mean for free ? fuck no :D 
and in anyway, I have contractual obligation not compatible with this

**Comment by Saikatsaha1996** [comment]
> you mean for free ? fuck no :D and in anyway, I have contractual obligation not compatible with this

You can add also donetion system ..

**Comment by Saikatsaha1996** [comment]
@djm34 can you please add ? 

![IMG_20220527_204209](https://user-images.githubusercontent.com/72664192/170728230-4d066a3d-a1fb-4133-b155-9b5b63b4bd18.jpg)

**Comment by Saikatsaha1996** [comment]
@djm34  can you add please verus algo ? :/

**Comment by Saikatsaha1996** [comment]
@djm34 sir solution wanted please

![Screenshot_2022-06-03-01-48-08-714_com termux](https://user-images.githubusercontent.com/72664192/171730805-6e81a74d-07c3-46f3-9da1-223814342ab2.jpg)

**Comment by Saikatsaha1996** [comment]
@djm34 Sir please add verushash algo for OpenCL :/
